export const FAVORITE_PENDING = "FAVORITE_PENDING"
export const FAVORITE_SUCCESS = "FAVORITE_SUCCESS"
export const FAVORITE_FAILURE = "FAVORITE_FAILURE"
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";

