

export const REQUEST_PENDING = "SIGNUP_REQUEST_PENDING";
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const LOGIN_REQUEST_SUCCESS= "LOGIN_REQUEST_SUCCESS"
export const REQUEST_FAILURE = "SIGNUP_REQUEST_FAILURE";
export const USERSIGN_OUT = "USERSIGN_OUT";